create or replace PACKAGE PKG_MANTENEDORES AS

    TYPE T_CURSOR IS REF CURSOR;

    -- MANTENEDOR CATEGORIA PLATO
    PROCEDURE LISTAR_CATEGORIA_PLATO (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);


    PROCEDURE AGREGAR_CATEGORIA_PLATO(PDESCRIPCION IN VARCHAR2,
                                     PERROR OUT VARCHAR2);

    PROCEDURE EDITAR_CATEGORIA_PLATO(PID_CATEGORIA IN NUMBER, PDESCRIPCION IN VARCHAR2,
                                     PERROR OUT VARCHAR2);

    PROCEDURE DESHABILITAR_CATEGORIA_PLATO(PID_CATEGORIA IN NUMBER,
                                     PERROR OUT VARCHAR2);

    PROCEDURE HABILITAR_CATEGORIA_PLATO(PID_CATEGORIA IN NUMBER,
                                     PERROR OUT VARCHAR2);                                 
    -- END MATENEREDOR CATEGORIA PLATO
    
     -- MANTENEDOR CATEGORIA PRODUCTO
    PROCEDURE LISTAR_CATEGORIA_PRODUCTO (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);


    PROCEDURE AGREGAR_CATEGORIA_PRODUCTO(PDESCRIPCION IN VARCHAR2,
                                     PERROR OUT VARCHAR2);

    PROCEDURE EDITAR_CATEGORIA_PRODUCTO(PID_CATEGORIA IN NUMBER, PDESCRIPCION IN VARCHAR2,
                                     PERROR OUT VARCHAR2);

    PROCEDURE DESHABILITAR_CATEGORIA_PRODUCT(PID_CATEGORIA IN NUMBER,
                                     PERROR OUT VARCHAR2);

    PROCEDURE HABILITAR_CATEGORIA_PRODUCTO(PID_CATEGORIA IN NUMBER,
                                     PERROR OUT VARCHAR2);                                 
    -- END MATENEREDOR CATEGORIA PRODUCTO
    
    -- MANTENEDOR USUARIO
    PROCEDURE LISTAR_USUARIO (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);


    PROCEDURE AGREGAR_USUARIO(PUSUARIO IN VARCHAR2, PCONTRASENA IN VARCHAR2, PNOMBRE IN VARCHAR2, PAPELLIDO IN VARCHAR2, PID_PERFIL IN NUMBER,
                                     PERROR OUT VARCHAR2);

    PROCEDURE EDITAR_USUARIO(PID_USUARIO IN VARCHAR2, PUSUARIO IN VARCHAR2, PCONTRASENA IN VARCHAR2, PNOMBRE IN VARCHAR2, PAPELLIDO IN VARCHAR2, PID_PERFIL IN NUMBER,
                                     PERROR OUT VARCHAR2);

    PROCEDURE DESHABILITAR_USUARIO(PID_USUARIO IN NUMBER,
                                     PERROR OUT VARCHAR2);

    PROCEDURE HABILITAR_USUARIO(PID_USUARIO IN NUMBER,
                                     PERROR OUT VARCHAR2);                                 
    -- END MATENEREDOR USUARIO
    
    --CLIENTE
    
    PROCEDURE AGREGAR_CLIENTE(PRUT IN VARCHAR2, PNOMBRE IN VARCHAR2, PID_CLIENTE_DEVUELTO OUT NUMBER,
                                     PERROR OUT VARCHAR2);
    --END CLIENTE
    
    --INGREDIENTE NO DESEADO
    PROCEDURE AGREGAR_INGREDIENTE_NO_DESEADO(PID_DETALLE_PEDIDO NUMBER, PID_INGREDIENTE NUMBER,
                                     PERROR OUT VARCHAR2);
    --END INGREDIENTE NO DESEADO
    
    --PLATO - INGREDIENTE PLATO
    PROCEDURE LISTAR_PLATO (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);
                              
    PROCEDURE AGREGAR_PLATO(PDESCRIPCION IN VARCHAR2, PRECETA IN CLOB, PIMAGEN IN BLOB, PPRECIO IN NUMBER, PID_CATEGORIA_PLATO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE EDITAR_PLATO(PID_PLATO IN NUMBER, PDESCRIPCION IN VARCHAR2, PRECETA IN CLOB, PIMAGEN IN BLOB, PPRECIO IN NUMBER, PID_CATEGORIA_PLATO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE HABILITAR_PLATO(PID_PLATO IN NUMBER,
                                     PERROR OUT VARCHAR2); 
                                     
    PROCEDURE DESHABILITAR_PLATO(PID_PLATO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE AGREGAR_INGREDIENTE_PLATO(PDESCUENTO_STOCK IN VARCHAR2, PID_PLATO IN NUMBER, PID_PRODUCTO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE ELIMINAR_INGREDIENTE_PLATO(PID_PLATO IN NUMBER,
                                     PERROR OUT VARCHAR2);
    
    PROCEDURE LISTAR_INGREDIENTE_PLATO(IO_CURSOR OUT T_CURSOR, PID_PLATO IN NUMBER,
                              PERROR OUT VARCHAR2);
    --END PLATO - INGREDIENTE PLATO
    
    --MENÚ - DETALLE MENÚ
    PROCEDURE LISTAR_MENU (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);
                              
    PROCEDURE AGREGAR_MENU(PDESCRIPCION IN VARCHAR2, PIMAGEN IN BLOB, PPRECIO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE EDITAR_MENU(PID_MENU IN NUMBER, PDESCRIPCION IN VARCHAR2, PIMAGEN IN BLOB, PPRECIO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE HABILITAR_MENU(PID_MENU IN NUMBER,
                                     PERROR OUT VARCHAR2); 
                                     
    PROCEDURE DESHABILITAR_MENU(PID_MENU IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE AGREGAR_DETALLE_MENU(PTIPO_MENU IN VARCHAR2, PID_MENU IN NUMBER, PID_PRODUCTO IN NUMBER, PID_PLATO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE ELIMINAR_DETALLE_MENU(PID_MENU IN NUMBER,
                                     PERROR OUT VARCHAR2);
    
    PROCEDURE LISTAR_DETALLE_MENU(IO_CURSOR OUT T_CURSOR, PID_MENU IN NUMBER,
                              PERROR OUT VARCHAR2);
    --END MENÚ - DETALLE MENÚ
    
    --PEDIDO - DETALLE PEDIDO
    PROCEDURE AGREGAR_PEDIDO(PCOMENSALES IN VARCHAR2, PFECHA_PEDIDO IN DATE, PTOTAL IN NUMBER, PMETODO_PAGO IN VARCHAR2, PID_CLIENTE IN NUMBER, PID_MESA IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE ACTUALIZAR_ESTADO_PEDIDO(PID_PEDIDO IN NUMBER, PID_ESTADO_PEDIDO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE CANCELAR_PEDIDO(PID_PEDIDO IN NUMBER, PID_ESTADO_PEDIDO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE AGREGAR_DETALLE_PEDIDO(PTIPO_PEDIDO IN VARCHAR2, PPRECIO IN NUMBER, PCANTIDAD IN NUMBER, PTOTAL IN NUMBER, PNOTAS IN VARCHAR2, PID_PRODUCTO IN NUMBER, PID_MENU IN NUMBER, PID_PLATO IN NUMBER, PID_PEDIDO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE ELIMINAR_DETALLE_PEDIDO(PID_PEDIDO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE LISTAR_DETALLE_PEDIDO(IO_CURSOR OUT T_CURSOR, PID_PEDIDO IN NUMBER,
                              PERROR OUT VARCHAR2);
    --END PEDIDO - DETALLE PEDIDO
    
    --SOLICITUD PROVEEDOR - DETALLE SOLICITUD
    PROCEDURE LISTAR_SOLICITUD_PROVEEDOR (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);
                              
    PROCEDURE AGREGAR_SOLICITUD_PROVEEDOR(PFECHA_SOLICITUD IN DATE, PTOTAL IN NUMBER, PID_PROVEEDOR IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE EDITAR_SOLICITUD_PROVEEDOR(PID_SOLICITUD IN NUMBER, PFECHA_SOLICITUD IN DATE, PTOTAL IN NUMBER, PID_PROVEEDOR IN NUMBER, PID_ESTADO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE AGREGAR_DETALLE_SOLICITUD(PCANTIDAD IN NUMBER, PPRECIO IN NUMBER, PTOTAL IN NUMBER, PID_SOLICITUD IN NUMBER, PID_PRODUCTO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE ELIMINAR_DETALLE_SOLICITUD(PID_SOLICITUD IN NUMBER,
                                     PERROR OUT VARCHAR2);
    
    PROCEDURE LISTAR_DETALLE_SOLICITUD(IO_CURSOR OUT T_CURSOR, PID_SOLICITUD IN NUMBER,
                              PERROR OUT VARCHAR2);
    --END SOLICITUD PROVEEDOR - DETALLE SOLICITUD
    
    --MESA
    PROCEDURE LISTAR_MESA (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);
                              
    PROCEDURE AGREGAR_MESA(PDESCRIPCION IN VARCHAR2, PPOSICION_AL IN NUMBER, PPOSICION_AN IN NUMBER, PMAX_PERSONAS IN NUMBER, PESTADO IN VARCHAR2,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE EDITAR_MESA(PID_MESA IN NUMBER, PDESCRIPCION IN VARCHAR2, PPOSICION_AL IN NUMBER, PPOSICION_AN IN NUMBER, PMAX_PERSONAS IN NUMBER, PESTADO IN VARCHAR2,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE HABILITAR_MESA(PID_MESA IN NUMBER,
                                     PERROR OUT VARCHAR2); 
                                     
    PROCEDURE DESHABILITAR_MESA(PID_MESA IN NUMBER,
                                     PERROR OUT VARCHAR2);
    --END MESA
    
    --PRODUCTO
    PROCEDURE LISTAR_PRODUCTO (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);
                              
    PROCEDURE AGREGAR_PRODUCTO(PDESCRIPCION IN VARCHAR2, PPRECIO_UNITARIO IN NUMBER, PSTOCK IN NUMBER, PID_CATEGORIA IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE EDITAR_PRODUCTO(PID_PRODUCTO IN NUMBER, PDESCRIPCION IN VARCHAR2, PPRECIO_UNITARIO IN NUMBER, PSTOCK IN NUMBER, PID_CATEGORIA IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE HABILITAR_PRODUCTO(PID_PRODUCTO IN NUMBER,
                                     PERROR OUT VARCHAR2); 
                                     
    PROCEDURE DESHABILITAR_PRODUCTO(PID_PRODUCTO IN NUMBER,
                                     PERROR OUT VARCHAR2);
    --END PRODUCTO
    
    --PROVEEDOR
    PROCEDURE LISTAR_PROVEEDOR (IO_CURSOR OUT T_CURSOR,
                              PERROR OUT VARCHAR2);
                              
    PROCEDURE AGREGAR_PROVEEDOR(PDESCRIPCION IN VARCHAR2, PCORREO IN NUMBER, PTELEFONO_CONTACTO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE EDITAR_PROVEEDOR(PID_PROVEEDOR IN NUMBER, PDESCRIPCION IN VARCHAR2, PCORREO IN NUMBER, PTELEFONO_CONTACTO IN NUMBER,
                                     PERROR OUT VARCHAR2);
                                     
    PROCEDURE HABILITAR_PROVEEDOR(PID_PROVEEDOR IN NUMBER,
                                     PERROR OUT VARCHAR2); 
                                     
    PROCEDURE DESHABILITAR_PROVEEDOR(PID_PROVEEDOR IN NUMBER,
                                     PERROR OUT VARCHAR2);
    --END PROVEEDOR
END PKG_MANTENEDORES;
